import type { Theme } from '../../types'
import { hljsDark } from '../../hljs-maps'

/** Linear */
export const theme: Theme = {
    id: 'linear-dark',
    name: 'Linear',
    description: '暗夜极客紫，编程教程的归宿',
    category: 'expressive',
    previewBackground: '#101114',
    hljsStyleMap: hljsDark,
    styles: {
      root: 'color:#f1f1f2;font-size:16px;line-height:1.8;word-break:break-word;',
      h1: 'margin:1.6em 0 0.8em;font-size:1.7em;font-weight:700;color:#ffffff;',
      h2: 'margin:1.5em 0 0.6em;font-size:1.35em;font-weight:600;color:#eeeeee;',
      h3: 'margin:1.3em 0 0.5em;font-size:1.15em;font-weight:600;color:#dddddd;',
      h4: 'margin:1.2em 0 0.5em;font-size:1.05em;font-weight:600;color:#f1f1f2;',
      h5: 'margin:1.1em 0 0.4em;font-size:1em;font-weight:600;color:#bbbbbb;',
      h6: 'margin:1em 0 0.4em;font-size:0.95em;font-weight:600;color:#999999;',
      p: 'margin:1em 0;',
      a: 'color:#8b93ff;text-decoration:none;border-bottom:1px solid #5e6ad2;',
      strong: 'font-weight:700;color:#ffffff;',
      em: 'font-style:italic;color:#bbbbbb;',
      del: 'text-decoration:line-through;color:#666666;',
      ul: 'margin:1em 0;padding-left:1.6em;',
      ol: 'margin:1em 0;padding-left:1.6em;',
      li: 'margin:0.4em 0;',
      blockquote: 'margin:1.3em 0;padding:0.8em 1.2em;border-left:4px solid #5e6ad2;background:#1a1a1a;color:#cccccc;',
      code: 'background:#1a1a2e;color:#8b93ff;padding:3px 6px;border-radius:4px;font-size:0.85em;font-family:"SF Mono",Consolas,monospace;',
      codeBlock: 'font-family:"SF Mono",Consolas,monospace;font-size:13px;line-height:1.5;color:#f1f1f2;',
      codeBlockWrapper: 'background:#1a1a2e;padding:20px;border-radius:8px;overflow-x:auto;margin:1.3em 0;',
      table: 'border-collapse:collapse;margin:1.3em 0;width:100%;font-size:0.95em;',
      thead: '',
      th: 'background:#1a1a2e;padding:10px 14px;text-align:left;font-weight:600;border:1px solid #333333;',
      td: 'padding:10px 14px;border:1px solid #333333;',
      tr: '',
      img: 'max-width:100%;display:block;margin:1.3em auto;border-radius:4px;',
      hr: 'border:none;border-top:1px solid #333333;margin:2em 0;',
    },
}
